/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: MIT
 */

// Offline tests of the generated client (src/api-autogenerated.js): https.request is replaced
// by a fake, so no cluster is needed. They check what each call sends: HTTP method, path,
// query string and body. Run with: npm test

const test = require("node:test");
const assert = require("node:assert/strict");
const { PveClient, Result } = require("../src/index.js");
const { fakeHttps, json, sent } = require("./fake-https.js");

/** Client with an API token and the calls it makes. */
function setUp(t) {
  const calls = fakeHttps(t, () => json(200, { data: null }));
  const client = new PveClient("pve01");
  client.apiToken = "root@pam!test=00000000-0000-0000-0000-000000000000";
  return { client, calls, last: () => sent(calls[calls.length - 1]) };
}

/** Arguments of a method with many parameters, placed by the names of its parameters. */
function argumentsByName(method, values) {
  const names = method
    .toString()
    .match(/\(([^)]*)\)/)[1]
    .split(",")
    .map((name) => name.trim());
  for (const name of Object.keys(values)) {
    assert.ok(names.includes(name), `the method has no parameter ${name}`);
  }
  return names.map((name) => values[name]);
}

test("version", async (t) => {
  const { client, last } = setUp(t);

  const result = await client.version.version();

  assert.ok(result instanceof Result);
  assert.deepEqual(last(), { method: "GET", path: "/api2/json/version", query: {}, body: null });
});

test("a node of the tree makes no request until a method is called", (t) => {
  const { client, calls } = setUp(t);

  const vm = client.nodes.get("pve01").qemu.get(100);
  vm.snapshot;

  assert.equal(calls.length, 0);
});

test("an optional parameter goes in the query string", async (t) => {
  const { client, last } = setUp(t);

  await client.cluster.resources.resources("vm");

  assert.equal(last().path, "/api2/json/cluster/resources");
  assert.deepEqual(last().query, { type: "vm" });
});

test("a parameter left out is not sent", async (t) => {
  const { client, calls, last } = setUp(t);

  await client.cluster.resources.resources();
  assert.deepEqual(last().query, {});
  assert.equal(calls[0].options.path, "/api2/json/cluster/resources");

  await client.cluster.resources.resources(null);
  assert.deepEqual(last().query, {});
});

test("the indexers build the path", async (t) => {
  const { client, last } = setUp(t);

  await client.nodes.get("pve01").qemu.get(100).status.current.vmStatus();

  assert.equal(last().method, "GET");
  assert.equal(last().path, "/api2/json/nodes/pve01/qemu/100/status/current");
});

test("create a snapshot: parameters in a JSON body, a boolean as 1 or 0", async (t) => {
  const { client, last } = setUp(t);
  const snapshot = client.nodes.get("pve01").qemu.get(100).snapshot;

  await snapshot.snapshot("snap1", "before the update", true);
  assert.equal(last().method, "POST");
  assert.equal(last().path, "/api2/json/nodes/pve01/qemu/100/snapshot");
  assert.deepEqual(last().body, {
    snapname: "snap1",
    description: "before the update",
    vmstate: 1,
  });

  await snapshot.snapshot("snap2", null, false);
  assert.deepEqual(last().body, { snapname: "snap2", vmstate: 0 });
});

test("delete a snapshot sends force in the query string", async (t) => {
  const { client, last } = setUp(t);

  await client.nodes.get("pve01").qemu.get(100).snapshot.get("snap1").delsnapshot(true);

  assert.equal(last().method, "DELETE");
  assert.equal(last().path, "/api2/json/nodes/pve01/qemu/100/snapshot/snap1");
  assert.deepEqual(last().query, { force: "1" });
  assert.equal(last().body, null);
});

test("delete a snapshot without parameters", async (t) => {
  const { client, calls, last } = setUp(t);

  await client.nodes.get("pve01").lxc.get(105).snapshot.get("snap1").delsnapshot();

  assert.equal(last().method, "DELETE");
  assert.equal(calls[0].options.path, "/api2/json/nodes/pve01/lxc/105/snapshot/snap1");
});

test("a parameter name with a dash is sent with the dash", async (t) => {
  const { client, last } = setUp(t);

  await client.nodes.get("pve01").qemu.get(100).status.start.vmStart("host");
  assert.equal(last().path, "/api2/json/nodes/pve01/qemu/100/status/start");
  assert.deepEqual(last().body, { "force-cpu": "host" });

  await client.cluster.ceph.restartBulk.restartBulk("osd", true, undefined, true, 60);
  assert.equal(last().method, "POST");
  assert.equal(last().path, "/api2/json/cluster/ceph/restart-bulk");
  assert.deepEqual(last().body, {
    "service-type": "osd",
    "dry-run": 1,
    "only-outdated": 1,
    timeout: 60,
  });
});

test("indexed parameters are sent one per index", async (t) => {
  const { client, last } = setUp(t);
  const qemu = client.nodes.get("pve01").qemu;

  // createVm has about a hundred parameters: vmid and netN are placed by their names
  await qemu.createVm(
    ...argumentsByName(qemu.createVm, {
      vmid: 100,
      netN: { 0: "model=virtio,bridge=vmbr0", 1: "model=virtio,bridge=vmbr1" },
    })
  );

  assert.equal(last().method, "POST");
  assert.equal(last().path, "/api2/json/nodes/pve01/qemu");
  assert.deepEqual(last().body, {
    vmid: 100,
    net0: "model=virtio,bridge=vmbr0",
    net1: "model=virtio,bridge=vmbr1",
  });
});

test("addIndexedParameter adds the values under the names of the API", (t) => {
  const { client } = setUp(t);
  const parameters = { cores: 4 };

  client.addIndexedParameter(parameters, "net", { 0: "a", 2: "c" });
  assert.deepEqual(parameters, { cores: 4, net0: "a", net2: "c" });

  client.addIndexedParameter(parameters, "scsi", null);
  client.addIndexedParameter(parameters, "ide", undefined);
  assert.deepEqual(parameters, { cores: 4, net0: "a", net2: "c" });
});

test("HA rule: the parameters are sent by name", async (t) => {
  const { client, last } = setUp(t);

  await client.cluster.ha.rules.createRule("rule1", "node-affinity", "vm:100,vm:101");
  assert.equal(last().method, "POST");
  assert.equal(last().path, "/api2/json/cluster/ha/rules");
  assert.deepEqual(last().body, {
    rule: "rule1",
    type: "node-affinity",
    resources: "vm:100,vm:101",
  });

  await client.cluster.ha.rules.get("rule1").updateRule("node-affinity", "comment", "abc");
  assert.equal(last().method, "PUT");
  assert.equal(last().path, "/api2/json/cluster/ha/rules/rule1");
  assert.deepEqual(last().body, { type: "node-affinity", delete: "comment", digest: "abc" });
});

test("Ceph health mute", async (t) => {
  const { client, last } = setUp(t);

  await client.cluster.ceph.healthMute.healthMuteIndex();
  assert.equal(last().method, "GET");
  assert.equal(last().path, "/api2/json/cluster/ceph/health-mute");

  await client.cluster.ceph.healthMute.get("OSD_DOWN").healthMute(true, undefined, "1h");
  assert.equal(last().method, "PUT");
  assert.equal(last().path, "/api2/json/cluster/ceph/health-mute/OSD_DOWN");
  assert.deepEqual(last().body, { value: 1, ttl: "1h" });
});

test("a route map entry takes the path values from the indexers", async (t) => {
  const { client, last } = setUp(t);

  await client.cluster.sdn.routeMaps.entries
    .get("map1")
    .entry.get(10)
    .deleteRouteMapEntry("lock-123");

  assert.equal(last().method, "DELETE");
  assert.equal(last().path, "/api2/json/cluster/sdn/route-maps/entries/map1/entry/10");
  assert.deepEqual(last().query, { "lock-token": "lock-123" });
});

test("the journal of a node sends its filters by name", async (t) => {
  const { client, last } = setUp(t);

  await client.nodes
    .get("pve01")
    .journal.journal(undefined, undefined, undefined, 100, undefined, "pveproxy");

  assert.equal(last().path, "/api2/json/nodes/pve01/journal");
  assert.deepEqual(last().query, { lastentries: "100", service: "pveproxy" });
});
